# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lan_ns_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 20, 761, 431))
        self.listView.setObjectName("listView")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(20, 460, 240, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.arpPoisonButton = QtWidgets.QPushButton(self.centralwidget)
        self.arpPoisonButton.setGeometry(QtCore.QRect(280, 460, 240, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.arpPoisonButton.setFont(font)
        self.arpPoisonButton.setObjectName("arpPoisonButton")
        self.synFloodButton = QtWidgets.QPushButton(self.centralwidget)
        self.synFloodButton.setGeometry(QtCore.QRect(540, 460, 240, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synFloodButton.sizePolicy().hasHeightForWidth())
        self.synFloodButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.synFloodButton.setFont(font)
        self.synFloodButton.setObjectName("synFloodButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "局域网网络安全测试工具"))
        self.refreshButton.setText(_translate("MainWindow", "刷新局域网存活主机列表"))
        self.arpPoisonButton.setText(_translate("MainWindow", "ARP缓存投毒（断网）测试"))
        self.synFloodButton.setText(_translate("MainWindow", "SYN Flood测试"))
